@baseUrl = https://localhost:7056/api/tarefas

### Criar Tarefa
POST {{baseUrl}}
Content-Type: application/json

{
  "titulo": "Estudar para a prova",
  "descricao": "Focar em Java e POO",
  "concluida": false
}

### Listar Todas as Tarefas
GET {{baseUrl}}

### Obter Tarefa por ID
GET {{baseUrl}}/1

### Atualizar Tarefa por ID
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "titulo": "Estudar para a prova de Java",
  "descricao": "Revisar também exercícios de Stream e Optional",
  "concluida": true
}

### Deletar Tarefa por ID
DELETE {{baseUrl}}/1
